language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.5
otp_release:
  - 17.5
  - 18.3
sudo: false # to use faster container based build environment
env:
  - MIX_ENV=test
install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
matrix:
  exclude:
    - otp_release: 17.5
      elixir: 1.2.5
    - otp_release: 18.3
      elixir: 1.0.5
